server:
  port: 9000
  tomcat: UTF-8
spring:
  redis:
    host: localhost
    port: 6379
    pool:
      max-active: 8
      #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
       #连接池最大空闲连接
      max-idle: 8
      #连接池最小空闲连接
      min-idle: 0
    #连接超时时间（毫秒）
    timeout: 0
  mvc:
    view:
      prefix: classpath*:/templates/
      suffix: .html
    static-path-pattern: /static/**
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html


